[package]
name = "com_calagopus_chat"
description = "A themed user and AI chat extension for the Calagopus Panel."
authors = ["Calagopus Chat contributors"]
version = "0.1.1"
edition = { workspace = true }
license = "GPL-3.0-or-later"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
compact_str = { workspace = true }
indexmap = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shared = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
